CREATE SCHEMA general;
CREATE SCHEMA business;
CREATE SCHEMA security;
CREATE SCHEMA history;

GRANT USAGE ON SCHEMA general TO postgres;
GRANT USAGE ON SCHEMA business TO postgres;
GRANT USAGE ON SCHEMA security TO postgres;
GRANT USAGE ON SCHEMA history TO postgres;

CREATE TABLE IF NOT EXISTS general.countries
(country_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 country_name VARCHAR(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS general.experience_levels
(experience_level_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 experience_level_title VARCHAR(20) NOT NULL
    );

CREATE TABLE IF NOT EXISTS security.roles
(role_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 role_title VARCHAR(21) NOT NULL
    );

CREATE TABLE IF NOT EXISTS security.users
(user_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 username VARCHAR(50) NOT NULL UNIQUE,
    password_hash bytea NOT NULL,
    role_id INT REFERENCES security.roles(role_id) ON DELETE RESTRICT NOT NULL
    password_salt bytea NOT NULL
    );

CREATE TABLE IF NOT EXISTS business.payrolls
(payroll_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 hourly_rate INT NOT NULL,
 gross_salary INT NOT NULL,
 net_salary INT NOT NULL,
 effective_date DATE NOT NULL,
 last_changed DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS business.departments
(department_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 department_name VARCHAR(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS business.jobs
(job_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 job_title VARCHAR(50) NOT NULL,
    department_id INT REFERENCES business.departments(department_id) ON DELETE RESTRICT NOT NULL
    );

CREATE TABLE IF NOT EXISTS business.branches
(branch_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 branch_name VARCHAR(50) NOT NULL,
    country_id INT REFERENCES general.countries(country_id) ON DELETE RESTRICT NOT NULL
    );

CREATE TABLE IF NOT EXISTS business.employees
(employee_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    job_id INT REFERENCES business.jobs(job_id) ON DELETE RESTRICT NOT NULL,
    experience_level_id INT REFERENCES business.experience_levels(experience_level_id) ON DELETE RESTRICT NOT NULL,
    payroll_id INT REFERENCES business.payrolls(payroll_id) NOT NULL UNIQUE,
    branch_id INT REFERENCES business.branches(branch_id) NOT NULL,
    email varchar(50) NOT NULL,
    user_id INT REFERENCES security.users(user_id) NOT NULL UNIQUE,
    date_of_birth DATE NOT NULL,
    employee_address VARCHAR(255) NOT NULL,
    nationality_id INT REFERENCES general.countries(country_id) ON DELETE RESTRICT NOT NULL,
    gender VARCHAR(20) NOT NULL,
    date_of_employment DATE NOT NULL,
    date_of_leaving DATE,
    remaining_vacation_days INT NOT NULL DEFAULT 25,
    used_vacation_days INT NOT NULL DEFAULT 0
    );

CREATE TABLE IF NOT EXISTS history.employees_job_history
(employee_job_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 employee_id INT REFERENCES business.employees(employee_id) ON DELETE CASCADE NOT NULL,
    job_id INT REFERENCES business.jobs(job_id) ON DELETE CASCADE NOT NULL,
    date_started DATE NOT NULL,
    date_ended DATE
    );

CREATE TABLE IF NOT EXISTS history.employees_branches_history
(employee_branch_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 employee_id INT REFERENCES business.employees(employee_id) ON DELETE CASCADE NOT NULL,
    branch_id INT REFERENCES business.branches(branch_id) ON DELETE CASCADE NOT NULL,
    date_started DATE NOT NULL,
    date_ended DATE
    );

CREATE TABLE IF NOT EXISTS history.vacations
(vacation_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 employee_id INT REFERENCES business.employees(employee_id) ON DELETE CASCADE NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL
    );